[build]
  command = "npm run build"
  publish = "dist"


# Redirects
[[redirects]]
  from = "/assets/PDFS/*"
  to = "/PDFS/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Build Post Processing
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true
[context.deploy-preview.processing.images]
  compress = false
