[build]
	command = "npx pnpm@6 install --shamefully-hoist --store-dir=.pnpm --frozen-lockfile && npx pnpm@6 build"
	publish = "dist"

[build.environment]
	NODE_VERSION = "16"
	NPM_FLAGS = "--version" # stop npm auto install

# Redirects
[[redirects]]
	from = "/assets/PDFS/*"
	to = "/PDFS/:splat"
	status = 301
	force = true

[[redirects]]
	from = "/contact"
	to = "/contact/inez"
	status = 302
	force = true

[[redirects]]
	from = "/contact/robin"
	to = "/contact/inez"
	status = 302
	force = true

[[redirects]]
	from = "/contact/robin-and-inez"
	to = "/contact/inez"
	status = 302
	force = true

[[redirects]]
	from = "/*"
	to = "/404.html"
	status = 404

# Build Post Processing
[build.processing]
	skip_processing = false
[build.processing.css]
	bundle = false
	minify = true
[build.processing.js]
	bundle = false
	minify = true
[build.processing.html]
	pretty_urls = false
[build.processing.images]
	compress = true
[context.deploy-preview.processing.images]
	compress = false
